version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    environment:
      - MYSQL_DATABASE=contosostore
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_SERVERNAME=localhost
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80